# Generated by Django 5.2.3 on 2025-07-23 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_role', '0003_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcycledProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upcycled_clothes', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='upcycled_clothes_images/')),
                ('quantity', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upcycler', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='upcycled_products', to='user_role.user')),
            ],
        ),
    ]
