# Generated by Django 5.2.3 on 2025-06-23 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trader', '0001_initial'),
        ('upcycler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('payment_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('condition', models.CharField(max_length=50)),
                ('listed_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trader_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.trader')),
                ('upcycler_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upcycler.upcycler')),
            ],
        ),
    ]
