# Generated by Django 5.2.3 on 2025-07-11 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
    ]
