# Generated by Django 5.2.3 on 2025-07-11 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20250711_1712'),
        ('user_role', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='trader',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'trader'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_as_trader', to='user_role.user'),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='upcycler',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'upcycler'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_as_upcycler', to='user_role.user'),
        ),
    ]
