# Generated by Django 5.2.3 on 2025-06-26 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('trader', 'Trader'), ('upcycler', 'Upcycler')], default='upcycler', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpcyclerClothesRequest',
            fields=[
                ('request', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='clothes_request_images/')),
                ('upcycler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_role.user')),
            ],
        ),
    ]
