# Generated by Django 5.2.3 on 2025-06-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_rename_catalogue_materialcatalogue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialcatalogue',
            name='material_type',
            field=models.CharField(choices=[('fabric', 'Fabric'), ('metal', 'Metal'), ('plastic', 'Plastic'), ('wood', 'Wood'), ('other', 'Other')], max_length=50, unique=True),
        ),
    ]
