# Generated by Django 5.2.3 on 2025-06-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_alter_materialcatalogue_material_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialcatalogue',
            name='material_type',
            field=models.CharField(choices=[('cotton', 'Cotton'), ('denim', 'Denim'), ('polyester', 'Polyester'), ('linel', 'Linel'), ('satin', 'Satin'), ('silk', 'Silk')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='materialcatalogue',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
