# Generated by Django 5.2.3 on 2025-07-23 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_role', '0003_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('condition', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('listed_at', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('account_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=30, null=True)),
                ('mpesa_checkout_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('result_code', models.CharField(blank=True, max_length=10, null=True)),
                ('result_description', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number_from_callback', models.CharField(blank=True, max_length=15, null=True)),
                ('amount_from_callback', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('trader', models.ForeignKey(blank=True, limit_choices_to={'role': 'trader'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_as_trader', to='user_role.user')),
                ('upcycler', models.ForeignKey(blank=True, limit_choices_to={'role': 'upcycler'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_as_upcycler', to='user_role.user')),
            ],
        ),
    ]
