# Generated by Django 5.2.3 on 2025-07-11 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upcycledproducts', '0001_initial'),
        ('user_role', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcycledproduct',
            name='upcycler',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='upcycled_products', to='user_role.user'),
        ),
    ]
