# Generated by Django 4.2.23 on 2025-06-20 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upcycler',
            fields=[
                ('upcycler', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpcyclerClothesRequest',
            fields=[
                ('request', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('upcycler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upcycler.upcycler')),
            ],
        ),
    ]
