# Generated by Django 5.2.3 on 2025-06-21 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upcycler',
            fields=[
                ('upcycler', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpcycledProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upcycled_clothes', models.CharField(max_length=50, unique=True)),
                ('quantity', models.IntegerField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upcycler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upcycler.upcycler')),
            ],
        ),
        migrations.CreateModel(
            name='UpcyclerClothesRequest',
            fields=[
                ('request', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('upcycler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upcycler.upcycler')),
            ],
        ),
    ]
