# Generated by Django 4.2.23 on 2025-06-20 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upcycler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcycledProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upcycled_clothes', models.CharField(max_length=50, unique=True)),
                ('quantity', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upcycler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upcycler.upcycler')),
            ],
        ),
    ]
