# Generated by Django 5.2.3 on 2025-06-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upcycler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcycledproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='upcycler',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upcycler_images/'),
        ),
        migrations.AddField(
            model_name='upcyclerclothesrequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='clothes_request_images/'),
        ),
        migrations.AlterField(
            model_name='upcycledproduct',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
