
# Generated by Django 5.2.3 on 2025-06-23 10:11

# Generated by Django 5.2.3 on 2025-06-23 10:24


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upcycler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcycledproduct',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
