# Generated by Django 5.2.3 on 2025-06-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upcycler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcycledproduct',
            name='upcycler',
        ),
        migrations.AlterField(
            model_name='upcycledproduct',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='UpcyclerClothesRequest',
        ),
        migrations.DeleteModel(
            name='Upcycler',
        ),
    ]
