# Generated by Django 5.2.3 on 2025-06-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upcycler', '0002_alter_upcycledproduct_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcycledproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upcycler_images/'),
        ),
        migrations.AddField(
            model_name='upcyclerclothesrequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upcycler_images/'),
        ),
    ]
