# Generated by Django 5.2.3 on 2025-06-24 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upcycler', '0002_upcycledproduct_image_upcycler_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcycler',
            name='image',
        ),
    ]
