# Generated by Django 4.2.23 on 2025-06-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upcycler', '0002_upcycledproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcycledproduct',
            name='quantity',
            field=models.IntegerField(max_length=50),
        ),
    ]
