# Generated by Django 5.2.3 on 2025-06-26 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upcycler', '0002_remove_upcycledproduct_upcycler_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upcycler',
            fields=[
                ('upcycler', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='upcycledproduct',
            name='upcycler',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='upcycler.upcycler'),
        ),
    ]
