# Generated by Django 5.2.3 on 2025-06-25 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upcycler', '0003_remove_upcycler_image'),
        ('upcycler', '0003_upcycledproduct_image_upcyclerclothesrequest_image'),
    ]

    operations = [
    ]
