# Generated by Django 5.2.3 on 2025-06-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upcycler', '0004_merge_20250625_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcycledproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upcycler_images/'),
        ),
    ]
