# Generated by Django 5.2.3 on 2025-07-10 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Material', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='trader',
        ),
    ]
