# Generated by Django 5.2.3 on 2025-07-11 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Material', '0003_material_trader'),
        ('user_role', '__first__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='user_role.user'),
        ),
    ]
