# Generated by Django 5.2.3 on 2025-06-24 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0002_material_image_trader_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trader',
            name='image',
        ),
    ]
