# Generated by Django 5.2.3 on 2025-06-25 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0002_material_image'),
        ('trader', '0003_remove_trader_image'),
    ]

    operations = [
    ]
