# Generated by Django 5.2.3 on 2025-07-23 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_role', '0003_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='material_images/')),
                ('condition', models.CharField(max_length=50)),
                ('listed_at', models.DateTimeField(auto_now_add=True)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='user_role.user')),
            ],
        ),
    ]
