# Generated by Django 5.2.3 on 2025-06-25 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaterialCatalogue',
            new_name='Catalogue',
        ),
    ]
