# Generated by Django 5.2.3 on 2025-06-25 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_rename_materialcatalogue_catalogue'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catalogue',
            new_name='MaterialCatalogue',
        ),
    ]
