# Generated by Django 5.2.3 on 2025-06-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_alter_materialcatalogue_material_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialcatalogue',
            name='material_type',
            field=models.CharField(choices=[('cotton', 'Cotton'), ('denim', 'Denim'), ('polyester', 'Polyester'), ('linel', 'Linel'), ('satin', 'Satin'), ('silk', 'Silk'), ('wool', 'Wool')], max_length=50),
        ),
    ]
