# Generated by Django 5.2.3 on 2025-07-21 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('trader', 'Trader'), ('upcycler', 'Upcycler')], default='upcycler', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UpcyclerClothesRequest',
            fields=[
                ('request', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='clothes_request_images/')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('upcycler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes_requests', to='user_role.user')),
            ],
        ),
    ]
