# Generated by Django 5.2.3 on 2025-07-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_role', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
