# Generated by Django 5.2.3 on 2025-07-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_role', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='dummy@example.com', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
