# Generated by Django 5.2.3 on 2025-07-25 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_role', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
